/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package green_supermarket.admin;

import green_supermarket.dao.EmailSending;
import green_supermarket.user.Login;
import static green_supermarket.user.Purchase.total;
import green_supermarket.user.UserDashboard;
import java.awt.Color;
import java.sql.SQLException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author saumya
 */
public class Payment extends javax.swing.JFrame {

    /**
     * Creates new form Payment
     */
    EmailSending emailSending;
    Color textPrimaryColor = new Color(30, 30, 30);
    Color primaryColor = new Color(255, 255, 255);
    
    public Payment() throws SQLException{
        this.emailSending = new EmailSending();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        holdername = new javax.swing.JTextField();
        cardno = new javax.swing.JTextField();
        captcha = new javax.swing.JTextField();
        getcvv = new javax.swing.JTextField();
        generatebutton = new javax.swing.JToggleButton();
        getcaptcha = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        paybutton = new javax.swing.JButton();
        Payhere = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Card holder's Name:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Card number:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("CVV");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));
        jPanel2.add(holdername, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 130, -1));
        jPanel2.add(cardno, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 130, -1));

        captcha.setEditable(false);
        captcha.setBackground(new java.awt.Color(255, 255, 255));
        captcha.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        captcha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                captchaActionPerformed(evt);
            }
        });
        jPanel2.add(captcha, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 130, 50));
        jPanel2.add(getcvv, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 130, -1));

        generatebutton.setBackground(new java.awt.Color(51, 204, 0));
        generatebutton.setForeground(new java.awt.Color(0, 0, 0));
        generatebutton.setSelected(true);
        generatebutton.setText("Generate Captcha");
        generatebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generatebuttonActionPerformed(evt);
            }
        });
        jPanel2.add(generatebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, -1, -1));

        getcaptcha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getcaptchaActionPerformed(evt);
            }
        });
        jPanel2.add(getcaptcha, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 130, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Captcha");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));

        paybutton.setBackground(new java.awt.Color(51, 204, 0));
        paybutton.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        paybutton.setText("PAY");
        paybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paybuttonActionPerformed(evt);
            }
        });
        jPanel2.add(paybutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, -1, -1));

        Payhere.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        Payhere.setText("Pay Here");
        jPanel2.add(Payhere, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void captchaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_captchaActionPerformed

    }//GEN-LAST:event_captchaActionPerformed

    private void generatebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generatebuttonActionPerformed
        String contain="1234567890abcdefghijklmnopqrstuvwxyz";
        Random r=new Random();
        StringBuilder sb=new StringBuilder(7);
        for(int i=0;i<7;i++)
        {
            sb.append(contain.charAt(r.nextInt(contain.length())));

        }
        String random=sb.toString();
        captcha.setText(random);

        // // TODO add your handling code here:
    }//GEN-LAST:event_generatebuttonActionPerformed

    private void getcaptchaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getcaptchaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getcaptchaActionPerformed

    private void paybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paybuttonActionPerformed
        String c, cvv,number,name;
        name=holdername.getText();
        c=getcaptcha.getText();
        number=cardno.getText();
        cvv=getcvv.getText();

        @SuppressWarnings("UnusedAssignment")
        boolean valid = true;
        if(name.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Enter your name");
            valid = false;
        }
        if (number.length() <13 || number.length() >16)
        {
            JOptionPane.showMessageDialog(null,"Enter card number with specified length");
            valid = false;

        }
        if(number.startsWith("1")||number.startsWith("2")||number.startsWith("8")||number.startsWith("9"))
        {
            JOptionPane.showMessageDialog(null,"Enter correct card number ");
            valid = false;
        }

        if (!c.equals(captcha.getText()))
        {
            JOptionPane.showMessageDialog(null,"Enter correct captcha");
            valid = false;
        }
        if(cvv.length()>4)
        {
            JOptionPane.showMessageDialog(null,"Enter correct cvv which is at the back of card");
            valid = false;
        }

        if(valid)
        {
            JOptionPane.showMessageDialog(null,"successfully payed");
            emailSending.sendemail(total);
            setDefault();
            this.dispose();        
        }
        else{
            JOptionPane.showMessageDialog(null,"Try again");
            Payment p = null;
            try {
                p = new Payment();
            } catch (SQLException ex) {
                Logger.getLogger(Payment.class.getName()).log(Level.SEVERE, null, ex);
            }
            p.setVisible(true);
            dispose();
        }

    }//GEN-LAST:event_paybuttonActionPerformed

    private void setDefault(){
        setVisible(false);
        UserDashboard.jPanel7.setBackground(primaryColor);
        UserDashboard.jPanel8.setBackground(primaryColor);
        UserDashboard.jLabel7.setForeground(textPrimaryColor);
        UserDashboard.jLabel8.setVisible(true);
        UserDashboard.jLabel18.setVisible(false);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Payment().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Payment.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Payhere;
    private javax.swing.JTextField captcha;
    public static javax.swing.JTextField cardno;
    private javax.swing.JToggleButton generatebutton;
    private javax.swing.JTextField getcaptcha;
    private javax.swing.JTextField getcvv;
    private javax.swing.JTextField holdername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton paybutton;
    // End of variables declaration//GEN-END:variables
}
